export const CHANGE_SEARCH_DATA = 'WEATHER_APP/SEARCH/CHANGE_SEARCH_DATA';
export const ADD_SEARCH_HISTORY = 'WEATHER_APP/SEARCH/ADD_SEARCH_HISTORY';

export const ADD_WEATHER = 'WEATHER_APP/WEATHERS/ADD_WEATHER';
export const CLOSE_WEATHER = 'WEATHER_APP/WEATHERS/CLOSE_WEATHER';

export const SET_LOADING = 'WEATHER_APP/STATUS/SET_LOADING';
export const SET_ERROR = 'WEATHER_APP/STATUS/SET_ERROR';

export const ADD_ZOOM = 'WEATHER_APP/SETTINGS/ADD_ZOOM';
export const OUT_ZOOM = 'WEATHER_APP/SETTINGS/OUT_ZOOM';
export const SET_MARK_FUNC = 'WEATHER_APP/SETTINGS/SET_MARK_FUNC';
export const SET_MARK_NEURON = 'WEATHER_APP/SETTINGS/SET_MARK_NEURON';