export const CHANGE_SEARCH_DATA = 'WEATHER_APP/CHANGE_SEARCH_DATA';
export const ADD_WEATHER = 'WEATHER_APP/ADD_WEATHER';
export const CLOSE_WEATHER = 'WEATHER_APP/CLOSE_WEATHER';
export const ADD_SEARCH_HISTORY = 'WEATHER_APP/ADD_SEARCH_HISTORY';
export const SET_LOADING = 'WEATHER_APP/SET_LOADING';
export const SET_ERROR = 'WEATHER_APP/SET_ERROR';